### ISSUE TITLE
Provide a way to use Namecheap API in sandbox mode

### ISSUE THREAD

**Issue by megheaiulian** [alastairparagas/NamecheapAPI#1]
Use https://api.sandbox.namecheap.com/xml.response when sandbox is enabled.

**Comment by megheaiulian** [comment]
#2

**Comment by megheaiulian** [comment]
@alastairparagas Can you please publish this on npm. Thanks :)

**Comment by alastairparagas** [comment]
@megheaiulian Oops. Will do!
